version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: max
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: streamify_db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: